# Generated by Django 4.2 on 2024-10-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_permanent_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
