# Generated by Django 4.2 on 2024-10-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_pdfdocument_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='file',
        ),
    ]
